### ISSUE TITLE
API call should include all ID spaces

### ISSUE THREAD

**Issue by vigliensoni** [digitalmusiclab/grail_api#1]
Given an API call for a specific ID space (e.g., ISRC). Should the API return all available ID spaces for that call? Or should the user specify which ones are needed? Any thoughts @baronemda @kurtbradd?

**Comment by vigliensoni** [comment]
By default, SolR returns the entire document. If only some fields are required, the query can be reduced by adding the parameter `fl` (http://wiki.apache.org/solr/CommonQueryParameters#fl)

For example, the following query returns only musicbrainz tracks IDs

```
http://localhost:8983/solr/grail/select?fl=musicbrainz&indent=on&q=*:*&wt=json
```

This parameter has to be explicitly declared in the Flask framework to be exposed in the public API

**Comment by kurtbradd** [comment]
@vigliensoni At the moment I believe it would be best to return the whole document, and not support selection of returned ID namespaces as we may change access patterns, and namespaces we support as we roll out the API.

Thoughts @baronemda ?

**Comment by MDBarone** [comment]
I think the ability to select which IDs you want in the return is an
important feature. We may change access patterns, but not for an ID space
like MusicBrainz.  I think it would be best to develop the API to handle
returning MusicBrainz at the very least.

**Comment by vigliensoni** [comment]
For now we are returning a JSON file with all ID spaces, but it will be very easy to implement a filter. Depending on the data we will end up having we may want to decide if we create a filter argument for the Solr query, or if we ask Solr to return everything and we post-process the response according to what the user want.

**Comment by vigliensoni** [comment]
I push the changes needed to have the most basic API call:

```
http://127.0.0.1:5000/api?artist_name=Bush
```

Returns all entries with Bush in the artist name

@baronemda, you now should be able to create the rest of the API calls based on this one.
