### ISSUE TITLE
Develop search parameters

### ISSUE THREAD

**Issue by MDBarone** [digitalmusiclab/grail_api#10]

**Comment by vigliensoni** [comment]
How accurate is the sample data you put in the data folder? As it is now, the first 60 rows have the same `isrc` as well as `track_name`, but different `spotify_artist` and `artist_name`

You should also split this issue in four issues, one for each bullet points

@baronemda

**Comment by vigliensoni** [comment]
It seems also that the sample data you created is just a very small sample of 60 lines duplicated until reaching 10000 entries. When querying for most artists I always get 167 results back.

**Comment by vigliensoni** [comment]
Search methods for artist were committed on f89d6c5e404fd9e65a62ccae3e3cc3eb50a2f3d6.

@baronemda , it would be great if you split this issue into several issues, otherwise we won't be able to close it.

**Comment by vigliensoni** [comment]
Any news about the sample data @baronemda ?

**Comment by MDBarone** [comment]
The processes should finish running in the next 48 hours. There were some issues with our postgres DB, so I am transferring the data over to MySQL presently. We will still be able to output the results as a flat file, but have the option to move into the sql plugin as well.

**Comment by vigliensoni** [comment]
Have you investigated how to write the dataimportHandler to use mysql
directly? You can check what I have in the `SQL_data_loading` branch

**Comment by MDBarone** [comment]
I have read the documentation you posted, but have not begun implementing this feature yet. I'll look into it once the tables have finished building.

**Comment by vigliensoni** [comment]
My shot would be having something functional working first. As the CSV
approach  is already working I would have this one up and running with the
proper data. Afterwards we may create a branch and start working in the
other approach.

Makes sense to you?

**Comment by MDBarone** [comment]
Agreed.
