### ISSUE TITLE
Create small SQL data dump

### ISSUE THREAD

**Issue by vigliensoni** [digitalmusiclab/grail_api#3]
And push it into the data folder of the repo.

**Comment by vigliensoni** [comment]
How much work implies flattening the SQL database file instead of sending a database dump? I wonder this because if we get a database dump we should write a dataConfig parser. 

Any thoughts about it @baronemda ?

**Comment by MDBarone** [comment]
By flattening, I assume you mean exporting as a .csv? Not a significant
amount of work. It's just as easy to export as .csv as .sql. Is the
dataConfig parser worth it, in your opinion? If .csv dumps will be easier
to implement, that works for me.

**Comment by vigliensoni** [comment]
Commit 39f6922a96413ddc34e8308c13b446b460fb1f93 closes this
