### ISSUE TITLE
Artist name in table

### ISSUE THREAD

**Issue by vigliensoni** [digitalmusiclab/grail_api#5]
Shouldn't the artist name be included in the table of

https://github.com/digitalmusiclab/grail_api/blob/master/data/track.tsv

If so, should it be named `g_artist_name`?

Thoughts @baronemda?

**Comment by MDBarone** [comment]
The artist name is in the artist table. I tried to denormalize the data into separate tables as much as reasonably possible. If this would be useful for querying, we can include this in the table
